### ISSUE TITLE
Move schema to top level?

### ISSUE THREAD

**Issue by owenvoke** [pxgamer/phpfile#3]
Currently the schema files contain a `class` key, with all the class details.

Perhaps we could either:
1. Move the schema to the top level
1. Make the top level an array, so there can be multiple classes per schema file

**Comment by bradietilley** [comment]
I say move schema to top level.

Array support should be handled externally (e.g. via a `foreach`) as each class will have a unique file and the current setup only supports one schema per output file.

**Comment by owenvoke** [comment]
I think that makes the most sense too. :+1: I'll move it tomorrow.
